### ISSUE TITLE
How to send a package from the Network Server to the end devices

### ISSUE THREAD

**Issue by yacoubhanna** [signetlabdei/lorawan#119] opened 2021-08-24 14:48 UTC
Hello,

Is it possible to send a package from the Network Server to the end devices? If Yes, how can I do that?

I did run a complete network example, but the Network Server is only receiving packages from the end devices. I need to do the opposite of that. 

I would really appreciate it if you can help me with that. 

Thank you.

**Comment by QiuYukang** [comment] 2021-08-25 08:10
This model does not support this function, I have a rough implementation here, you can refer to it https://github.com/QiuYukang/lorawan/tree/class-c

**Comment by yacoubhanna** [comment] 2021-08-25 14:30
Thank you for your response. Is your modified version has already implemented the issue that I'm facing or do I still have to write the code? Because what I'm trying to do is modify the network server example in order for the network server to send the package to the end devices. Is it possible to do that using your modified version?

**Comment by QiuYukang** [comment] 2021-08-25 15:02
Yes，the network server can send the packet to the end devices，you only have to change `macHelper.SetDeviceType (LorawanMacHelper::ED_A)` to `macHelper.SetDeviceType (LorawanMacHelper::ED_C)` in you sim script，and you can use `NetworkServer.Send` to send a packet to the specific class-c end-device.
see  https://github.com/QiuYukang/lorawan/blob/01816f45623ba964738d062216fc1830d9f3b362/model/network-server.h#L105

**Comment by yacoubhanna** [comment] 2021-08-25 18:11
I'm trying to modify the network-server-example. I did change `macHelper.SetDeviceType (LorawanMacHelper::ED_A)` to `macHelper.SetDeviceType (LorawanMacHelper::ED_C)`. And when I run it I get an error and I believe that is because I didn't add `NetworkServer.Send` command. 

The error that I'm getting is 
```
assert failed. cond="m_ptr", msg="Attempted to dereference zero pointer", +0.000000000s -1 file=./ns3/ptr.h, line=630
terminate called without an active exception
```
Therefore, I'm trying to add the `NetworkServer.Send` 
and now, I have this 
```
  Ptr<Packet> data = Create<Packet> (10);
  //NetworkServer.Send(Ptr<Packet> data, LoraDeviceAddress endDevices);
```
I was able to generate the data. However, I'm not able to get the `LoraDeviceAddress` and the `endDevices` 

How can I get these? 
is this one has something to do with it?
```
Ptr<LorawanMac> edMac1 = endDevices.Get (1)->GetDevice (0)->GetObject<LoraNetDevice> ()->GetMac ();
```

Thanks.

**Comment by QiuYukang** [comment] 2021-08-26 03:13
Hi @yacoubhanna! I have added an example, you can see this https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/examples/class-c-end-device-example.cc#L175

Try to run `./waf --run class-c-end-device-example`，you can see this log:
```bash
....
+21.320965613s 0 ClassCEndDeviceLorawanMac:Receive(): Found a downlink packet.
+21.320965613s 0 ClassCEndDeviceLorawanMac:Receive(): Frame Header: Address=0110110|0000000000000011101001000
ADR=0
ADRAckReq=0
ACK=0
FPending=0
FOptsLen=0
FCnt=1
FPort=0

+21.320965613s 0 ClassCEndDeviceLorawanMac:Receive(): This is a unicast frame and the msg is for us!
....
```

**Comment by yacoubhanna** [comment] 2021-08-26 03:35
Hello @QiuYukang Great thank you so much. I really appreciated it. I see that the message is unicasted to a specific end device. Is it possible to do a broadcast !! Do I have to change the address to 0xFFF in order to do a broadcast message?

**Comment by QiuYukang** [comment] 2021-08-26 04:26
In order to send a broadcast, you can use `LoraDeviceAddress::LoraDeviceAddress (uint8_t nwkId, uint32_t nwkAddr)`, then make nwkId = `0x7F` and nwkAdd = `0x1FFFFFF`.

see these codes：
- https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/model/class-c-end-device-lorawan-mac.cc#L164
- https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/model/lora-device-address.cc#L166

**Comment by yacoubhanna** [comment] 2021-08-26 15:03
Hello @QiuYukang. Thank you it is working.

**Comment by asmanuha** [comment] 2021-08-30 16:57
what a great jobs.. thanks @QiuYukang 
anyway I have tried my best to follow and modify my code as your guidance. However I have problem here:

../src/lorawan/model/network-server.cc: In member function ‘void ns3::lorawan::NetworkServer::Send(ns3::Ptr<ns3::Packet>, ns3::lorawan::LoraDeviceAddress)’:
../src/lorawan/model/network-server.cc:192:16: error: ‘class ns3::lorawan::NetworkScheduler’ has no member named ‘DoSend’; did you mean ‘DoSet’?
   m_scheduler->DoSend(data, deviceAddress, 2);
                ^~~~~~
                DoSet
In file included from ./ns3/object.h:27:0,
                 from ./ns3/network-server.h:25,
                 from ../src/lorawan/model/network-server.cc:22:
./ns3/ptr.h: In instantiation of ‘ns3::Ptr<T>::Ptr(const ns3::Ptr<U>&) [with U = ns3::lorawan::EndDeviceLorawanMac; T = ns3::lorawan::ClassAEndDeviceLorawanMac]’:
../src/lorawan/model/network-server.cc:153:34:   required from here
./ns3/ptr.h:748:24: error: invalid conversion from ‘ns3::lorawan::EndDeviceLorawanMac*’ to ‘ns3::lorawan::ClassAEndDeviceLorawanMac*’ [-fpermissive]
   : m_ptr (PeekPointer (o))
            ~~~~~~~~~~~~^~~


could you give me advice,regarding above issue? 
what 's wrong with my code?

**Comment by asmanuha** [comment] 2021-08-30 17:05
ooh... i found the answer about my first problem
just check your code in src/lorawan/modelnetwork-scheduler.h and add this line

/**
   * Send data to the end device in the specified recieve window
   */
  void DoSend(Ptr<Packet> data, LoraDeviceAddress deviceAddress, int window);

**Comment by asmanuha** [comment] 2021-08-30 18:18
still can't figure out what happen here

[1328/2134] Compiling src/lorawan/model/network-server.cc
In file included from ./ns3/object.h:27:0,
                 from ./ns3/network-server.h:25,
                 from ../src/lorawan/model/network-server.cc:22:
./ns3/ptr.h: In instantiation of ‘ns3::Ptr<T>::Ptr(const ns3::Ptr<U>&) [with U = ns3::lorawan::EndDeviceLorawanMac; T = ns3::lorawan::ClassAEndDeviceLorawanMac]’:
../src/lorawan/model/network-server.cc:153:34:   required from here
./ns3/ptr.h:748:24: error: invalid conversion from ‘ns3::lorawan::EndDeviceLorawanMac*’ to ‘ns3::lorawan::ClassAEndDeviceLorawanMac*’ [-fpermissive]
   : m_ptr (PeekPointer (o))
            ~~~~~~~~~~~~^~~

I really appreciate your help.. :)


and here also the problem that i found out: (I rename the "class-c-end-device-example.cc" as "classC.cc" under scratch) -- and I check that the example source code also put "GetMac instead of GetPhy" -- so where should i add the GetMac argument?

../scratch/classC.cc: In function ‘int main(int, char**)’:
../scratch/classC.cc:131:52: error: ‘class ns3::lorawan::LorawanMac’ has no member named ‘GetMac’; did you mean ‘GetPhy’?
   Ptr<EndDeviceLorawanMac> edLorawanMac1 = edMac1->GetMac ()->GetObject<EndDeviceLorawanMac> ();
                                                    ^~~~~~
                                                    GetPhy

many thanks

**Comment by QiuYukang** [comment] 2021-08-31 02:54
Hi @asmanuha if you want to send a packet from the Network Server to the end devices，you have to checkout to branch [QiuYukang/lorawan/class-c](https://github.com/QiuYukang/lorawan).

Are you going to get phy? 
Refer to this [example](https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/examples/class-c-end-device-example.cc#L131)，you can use：
```c++
Ptr<ClassCEndDeviceLorawanMac> edLorawanMac1 = edMac1->GetObject<ClassCEndDeviceLorawanMac> ();
Ptr<LoraPhy> edPhy = edLorawanMac1->GetPhy();
```
or
```c++
Ptr<ClassAEndDeviceLorawanMac> edLorawanMac1 = edMac1->GetObject<ClassAEndDeviceLorawanMac> ();
Ptr<LoraPhy> edPhy = edLorawanMac1->GetPhy();
```
Whether you use `ClassAEndDeviceLorawanMac` or `ClassCEndDeviceLorawanMac` depends on the type of end-device.

**Comment by asmanuha** [comment] 2021-08-31 07:12
hi @QiuYukang thanks for your answer, actually I want to **"GetMac"** so that I can see information in the MAC layer.

Still have a problem like 

Waf: Entering directory `/home/lpdp/qkdnetsim-dev-master/build'
[1329/2134] Compiling src/lorawan/model/network-server.cc
In file included from ./ns3/object.h:27:0,
                 from ./ns3/network-server.h:25,
                 from ../src/lorawan/model/network-server.cc:22:
./ns3/ptr.h: In instantiation of ‘ns3::Ptr<T>::Ptr(const ns3::Ptr<U>&) [with U = ns3::lorawan::EndDeviceLorawanMac; T = ns3::lorawan::ClassAEndDeviceLorawanMac]’:
../src/lorawan/model/network-server.cc:153:34:   required from here
./ns3/ptr.h:748:24: error: invalid conversion from ‘ns3::lorawan::EndDeviceLorawanMac*’ to ‘ns3::lorawan::ClassAEndDeviceLorawanMac*’ [-fpermissive]
   : m_ptr (PeekPointer (o))
            ~~~~~~~~~~~~^~~

I put the same code as provided in the  code from "class-c-end-device-example.cc"
  // Set message type (Default is unconfirmed)
   Ptr<LorawanMac> edMac1 = endDevices.Get (0)->GetDevice (0)->GetObject<LoraNetDevice> ()->GetMac ();
  Ptr<ClassCEndDeviceLorawanMac> edLorawanMac1 = edMac1->GetObject<ClassCEndDeviceLorawanMac> ();


I have check several time your source code in model/network-server.cc ;  and, here my modification ( I think it's exactly same) start from line 144 to 153
line 144 --                // Get the MAC
line 145 --                // Ptr<ClassAEndDeviceLorawanMac> edLorawanMac =
line 146 --               //   loraNetDevice->GetMac ()->GetObject<ClassAEndDeviceLorawanMac> ();
line 147 --               // Ptr<ClassCEndDeviceLorawanMac> edLorawanMac1 =
line 148 --               //   loraNetDevice->GetMac ()->GetObject<ClassCEndDeviceLorawanMac> ();
line 149 --                 Ptr<EndDeviceLorawanMac> edLorawanMac =
line 150 --                 loraNetDevice->GetMac ()->GetObject<EndDeviceLorawanMac> (); 
line 151 --
line 152 --              // Update the NetworkStatus about the existence of this node
line 153 --                 m_status->AddNode (edLorawanMac);

Many thanks for your help and explanantion.. it bright up my day :)

**Comment by QiuYukang** [comment] 2021-08-31 08:19
hi @asmanuha ，can you upload the script file which you has modified, so that I can help you troubleshoot the problem better?

**Comment by asmanuha** [comment] 2021-08-31 09:27
hi **@QiuYukang**  Many thanks for your fast response,
I have step by step as here

1. Create file "lorawan/model/class-c-end-device-lorawan-mac.h" copy paste from Reference -->  https://github.com/QiuYukang/lorawan/blob/qiu_dev/model/class-c-end-device-lorawan-mac.h 

2. Create file "lorawan/model/class-c-end-device-lorawan-mac.cc" copy paste from Reference -->  https://github.com/QiuYukang/lorawan/blob/qiu_dev/model/class-c-end-device-lorawan-mac.cc

3. Add a line of code in "lorawan/model/lora-device-address.h"  Reference -->  https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/model/lora-device-address.h
> bool IsBroadcast ();

4. Add 5 line of code in file "lorawan/model/lora-device-address.cc" around line no 165
bool 
LoraDeviceAddress::IsBroadcast ()
{
  return m_nwkId.Get () == 0x7F && m_nwkAddr.Get () == 0x1FFFFFF;
}
Reference --> https://github.com/QiuYukang/lorawan/blob/a8a6cf64de262a2d6af6d1b623807bbbc970e4d2/model/lora-device-address.cc#L166

5.Add a line of code in file "lorawan/model/network-server.h"
 void Send(Ptr<Packet> data, LoraDeviceAddress deviceAddress);
Refrence --> https://github.com/QiuYukang/lorawan/blob/01816f45623ba964738d062216fc1830d9f3b362/model/network-server.h

6. Add line of codes in File "lorawan/model/network-server.cc" 

== around  line number 184
void NetworkServer::Send(Ptr<Packet> data, LoraDeviceAddress deviceAddress)
{
  NS_LOG_FUNCTION(this << data << deviceAddress);

  m_scheduler->DoSend(data, deviceAddress, 2);
}

== around line 144
// Get the MAC
 // Ptr<ClassAEndDeviceLorawanMac> edLorawanMac =
 //   loraNetDevice->GetMac ()->GetObject<ClassAEndDeviceLorawanMac> ();
 // Ptr<ClassCEndDeviceLorawanMac> edLorawanMac1 =
 //   loraNetDevice->GetMac ()->GetObject<ClassCEndDeviceLorawanMac> ();
  Ptr<EndDeviceLorawanMac> edLorawanMac =
      loraNetDevice->GetMac ()->GetObject<EndDeviceLorawanMac> ();

  // Update the NetworkStatus about the existence of this node
  m_status->AddNode (edLorawanMac);

===
7. disable/ make it as command -the "private"- in file lorawan/model/end-device-lorawan-mac.h (around line 434) 
//private:     
Reference --> https://github.com/QiuYukang/lorawan/blob/01816f45623ba964738d062216fc1830d9f3b362/model/end-device-lorawan-mac.h

8. Add line of codes in file "lorawan/model/end-device-lorawan-mac.cc"
===== around line number 155 up to 162

  // Check that payload length is below the allowed maximum
  if (packet->GetSize () > m_maxAppPayloadForDataRate.at (m_dataRate))
    {
      NS_LOG_WARN ("Attempting to send a packet larger than the maximum allowed"
                   << " size at this DataRate (DR" << unsigned(m_dataRate) <<
                   "). Transmission canceled.");
      return;
    }

=====Also add a line of code around line number 285
 m_currentFCnt++;

Reference --> https://github.com/QiuYukang/lorawan/blob/qiu_dev/model/end-device-lorawan-mac.cc

9. Add a line of codes in File "lorawan/model/network-scheduler.h"
== line number  
  void DoSend(Ptr<Packet> data, LoraDeviceAddress deviceAddress, int window);

10. Add line of codes in file  "lorawan/model/network-scheduler.cc"
Reference --> https://github.com/QiuYukang/lorawan/blob/01816f45623ba964738d062216fc1830d9f3b362/model/network-scheduler.cc

void 
NetworkScheduler::DoSend(Ptr<Packet> data, LoraDeviceAddress deviceAddress, int window)
{
  NS_LOG_FUNCTION(this << data << deviceAddress << window);
  
  // Broadcast frame
  if (deviceAddress.IsBroadcast ()) 
    {
      // Find all avalible gateways to send broadcast
      std::list<Address> gwAddresses = m_status->GetAvalibleGatewaysForBroadcast ();

      // Create a broadcast frame
      Ptr<Packet> packet = m_status->CreateBroadcastPacket (data);

      // Send the packet through all avalible gateways
      for (auto it = gwAddresses.begin(); it != gwAddresses.end(); it++)
        {
          NS_LOG_DEBUG ("Send a broadcast frame through gateway " << *it << " .");
          m_status->SendThroughGateway (packet, *it);
        }
    } 
  // Unicast frame
  else 
    {
      // Check whether we can send a reply to the device, again by using
      // NetworkStatus
      Address gwAddress = m_status->GetBestGatewayForDevice (deviceAddress, window);

      NS_LOG_DEBUG ("Found available gateway with address: " << gwAddress);
      if(gwAddress == Address())
      {
        NS_LOG_DEBUG ("No suitable gateway found.");
        return;
      }

      // Create a frame
      Ptr<Packet> packet = m_status->GetDataPacketForDevice(data, deviceAddress, window);
      
      // Send the reply through that gateway
      m_status->SendThroughGateway (packet, gwAddress);
    }
}


11. Add a header in File "model/network-status.h"
======header
#include "ns3/class-c-end-device-lorawan-mac.h"

===== and add code in line no. 92
  std::list<Address> GetAvalibleGatewaysForBroadcast ();

===== and add codes in line no. 99
  Ptr<Packet> CreateBroadcastPacket (Ptr<Packet> data);

===== and add codes in line no. 118
Ptr<Packet> GetDataPacketForDevice (Ptr<Packet> data, LoraDeviceAddress edAddress, int windowNumber);

12. Add Code in File "model/network.status.cc" 
Reference --> https://github.com/QiuYukang/lorawan/blob/01816f45623ba964738d062216fc1830d9f3b362/model/network-status.cc

==========line 168 to 223

std::list<Address> 
NetworkStatus::GetAvalibleGatewaysForBroadcast ()
{
  NS_LOG_FUNCTION (this);

  std::list<Address> gwAddress = std::list<Address>();
  
  std::map<Address, Ptr<GatewayStatus>>::iterator iter;
  for (auto &iter : m_gatewayStatuses)
    {
      // fixme: this frequency should be set according to different regions, not fixed at 869.525 (ED region)
      if (iter.second->IsAvailableForTransmission (869.525))
        {
          gwAddress.push_back (iter.first);
        }
    }

  return gwAddress;
}

Ptr<Packet> 
NetworkStatus::CreateBroadcastPacket (Ptr<Packet> data)
{
  LoraDeviceAddress address;
  address.SetNwkID (0x7F);
  address.SetNwkAddr (0x1FFFFFF);
  
  LorawanMacHeader mHdr;
  mHdr.SetMType (LorawanMacHeader::UNCONFIRMED_DATA_DOWN);
  mHdr.SetMajor (1);

  LoraFrameHeader fHdr;
  fHdr.SetAsDownlink ();
  fHdr.SetFPort (1);  // TODO Use an appropriate frame port based on the application
  fHdr.SetAddress (address);
  fHdr.SetAdr (false);
  fHdr.SetAck (false);
  fHdr.SetAdrAckReq (0);
  fHdr.SetFCnt (0);
  fHdr.SetFPending (false);

  Ptr<Packet> packet = data->Copy();

  // Add packet tag
  LoraTag tag;
  // fixme: this frequency should be set according to different regions, not fixed at 869.525 (EU region)
  tag.SetFrequency (869.525);
  // fixme: this DataRate should be set according to different regions, not fixed at DR0 (EU region)
  tag.SetDataRate (0);

  packet->AddHeader (fHdr);
  packet->AddHeader (mHdr);
  packet->AddPacketTag (tag);

  return packet;
}

===== =====line 241 to 246

Ptr<ClassAEndDeviceLorawanMac> classAMac =
      edStatus->GetMac ()->GetObject<ClassAEndDeviceLorawanMac> ();
  Ptr<ClassCEndDeviceLorawanMac> classCMac =
      edStatus->GetMac ()->GetObject<ClassCEndDeviceLorawanMac> ();
  NS_LOG_DEBUG ("Class_A_Mac:" << classAMac << "  Class_C_Mac:" << classCMac);
  NS_ASSERT (classAMac != 0 || classCMac != 0);

=========modify loratag  in line 248 to 278

// Apply the appropriate tag
  LoraTag tag;
  switch (windowNumber)
    {
    case 1:
      if (classAMac != 0)
        {
          tag.SetDataRate (classAMac->GetFirstReceiveWindowDataRate ());
        }
      else if (classCMac != 0)
        {
          tag.SetDataRate (classCMac->GetFirstReceiveWindowDataRate ());
        }
      tag.SetFrequency (edStatus->GetFirstReceiveWindowFrequency ());
      break;
    case 2:
      if (classAMac != 0)
        {
          tag.SetDataRate (classAMac->GetSecondReceiveWindowDataRate ());
        }
      else if (classCMac != 0)
        {
          tag.SetDataRate (classCMac->GetSecondReceiveWindowDataRate ());
        }
      tag.SetFrequency (edStatus->GetSecondReceiveWindowFrequency ());
      break;
    }

  packet->AddPacketTag (tag);
  return packet;
}


==== == make changes in 235 up to 246
Ptr<Packet>
NetworkStatus::GetReplyForDevice (LoraDeviceAddress edAddress, int windowNumber)
{
  // Get the reply packet
  Ptr<EndDeviceStatus> edStatus = m_endDeviceStatuses.find (edAddress)->second;
  Ptr<Packet> packet = edStatus->GetCompleteReplyPacket ();
  Ptr<ClassAEndDeviceLorawanMac> classAMac =
      edStatus->GetMac ()->GetObject<ClassAEndDeviceLorawanMac> ();
  Ptr<ClassCEndDeviceLorawanMac> classCMac =
      edStatus->GetMac ()->GetObject<ClassCEndDeviceLorawanMac> ();
  NS_LOG_DEBUG ("Class_A_Mac:" << classAMac << "  Class_C_Mac:" << classCMac);
  NS_ASSERT (classAMac != 0 || classCMac != 0);

**Comment by QiuYukang** [comment] 2021-08-31 12:40
Hi @asmanuha, did you make these changes based on the [latest commit](https://github.com/signetlabdei/lorawan/tree/9f373c23076c3e821e6a6104bde8409e1a24a9fe) of `signetlabdei/lorawan/develop`? 
I don’t think my changes will work well on the latest branch。
In fact, I made these changes based on [this commit](https://github.com/signetlabdei/lorawan/tree/474402318be571a6eda4fc214b22ebe5908942ed), you can refer to it：
https://github.com/QiuYukang/lorawan/compare/474402318be571a6eda4fc214b22ebe5908942ed...a8a6cf64de262a2d6af6d1b623807bbbc970e4d2

**Comment by asmanuha** [comment] 2021-08-31 13:00
Hi **@QiuYukang** Thanks for your help... Yes, I did make the changes from the latest version.
So to make it easier should I just need to remove folder "lorawan" folder in the src/ -- just reinstall)  lorawan in the ns3 and changes the lorawan source based on this reference : https://github.com/signetlabdei/lorawan/tree/474402318be571a6eda4fc214b22ebe5908942ed ?

Then after the Network server manage to send packet to End Device, I can upgrade the lorawan version. is it right?

My final goal is : Network server can send the "a piece of security information" to End Device, and the end device can follow up that information.

**Comment by QiuYukang** [comment] 2021-08-31 14:06
Hi @asmanuha, I have merged my branch with the latest commit of `signetlabdei/lorawan/develop`, the latest version is in [`QiuYukang/lorawan/class-c`](https://github.com/QiuYukang/lorawan).

I think you can do your work on [`QiuYukang/lorawan/class-c`](https://github.com/QiuYukang/lorawan) to send the "a piece of security information" to End Device.

**Comment by asmanuha** [comment] 2021-08-31 14:32
Hi **@QiuYukang** many thanks for your help .. I really appreciate your hard work.
OK, I will try now

**Comment by asmanuha** [comment] 2021-09-01 07:32
Hi **@QiuYukang** . It Works !!!
Thank you so much ツ
it's good work...

**Comment by yacoubhanna** [comment] 2021-09-20 03:40
Hello @asmanuha , I'm facing the same problem now. In which I'm trying to send a packet or message from the network server to the end device and getting the same error as yours. Did you have to modify a lot of stuff or just add some codes? I would really appreciate it if you can share what you did in order to work. 

Thank you.

**Comment by asmanuha** [comment] 2021-09-20 05:30
Hi, @yacoubhanna. Yes,  I modified 13 files according to the information. I recorded every modification, and the total is around 600 line codes. I think it is not polite to add a very long message in this command section. I am still a newbie playing with Github, and I don't know where the best way to put the modification file is (which the code itself is not mine); so that everyone can easily use it.

**Comment by yacoubhanna** [comment] 2021-09-20 14:35
Hello @asmanuha, thanks for your response. I think what you can do is to upload the helper and the model folders with the code example to your Github and place only the modified files there the .h and .cc files, and you can mention that these are modified files from the LoRaWan source, and I can modify the files from my end. If it is possible. @QiuYukang since you are one of the contributors is it okay to do this?  

Thank you.

**Comment by yacoubhanna** [comment] 2021-09-21 13:22
Hello @asmanuha. I believe there will be no problem posting the modified files on your Github or maybe send them by email. Please let me know if you can help me with that. Since I'm still having some trouble with it. 

Thank you.

**Comment by asmanuha** [comment] 2021-10-02 07:00
[Class C LoRaWAN Modification - compiled by asmanuha.pdf](https://github.com/signetlabdei/lorawan/files/7271033/Class.C.LoRaWAN.Modification.-.compiled.by.asmanuha.pdf)

Hi @QiuYukang, many thanks for your help, and since @yacoubhanna gave me a question in my Github, I put the configuration's change there. Here is the step-by-step link: https://github.com/asmanuha/LoRaWAN/issues/1#issuecomment-932696356 or you can download the attached file above.

*sorry for my late response

**Comment by yacoubhanna** [comment] 2021-10-03 18:38
Hello, @asmanuha Thank you so much.

**Comment by DvdMgr** [comment] 2021-11-19 15:16
It looks like this was solved. Thanks to everyone that got involved! 

We have considered adding this as a feature in the past, and probably will at some point in the future - unfortunately, other commitments make it a bit hard as of now to follow all developments and actively work on new feature. 

Closing for now.

**Closed as completed by DvdMgr** 2021-11-19 15:16 UTC

**Comment by mouaadh1010** [comment] 2022-10-25 22:04
Hi everyone ,
in lorawan's network-server-example, I cannot define, configure and interpret the ED address, GW address and NewServ address, if you can help me I will be very [grateful
![Sans titre 2](https://user-images.githubusercontent.com/105976201/197890941-7139f1ff-0fa2-444f-8f53-0aaa5cee6be8.png)
